#机器人几何参数
footprint: [[-0.2, -0.15], [-0.2, 0.15], [0.2, 0.15], [0.2, -0.15]]
footprint_padding: 0.01

#传感器参数
obstacle_range: 2.5
raytrace_range: 3.0
transform_tolerance: 0.2

#障碍物层参数
obstacle_layer:
  enabled: true
  combination_method: 1
  track_unknown_space: true
  obstacle_range: 2.5
  raytrace_range: 3.0
  observation_sources: laser_scan_sensor
  laser_scan_sensor: {
    sensor_frame: base_scan,
    data_type: LaserScan,
    topic: scan,
    marking: true,
    clearing: true,
    min_obstacle_height: 0.0,
    max_obstacle_height: 2.0
  }

#膨胀层参数
inflation_layer:
  enabled: true
  cost_scaling_factor: 5.0
  inflation_radius: 0.7

static_layer:
  enabled: true
