# bomb sites [x, y, z]
bomb_sites:
  - [5.0, 5.0, 0.0]  # A点
  - [-5.0, 5.0, 0.0]  # B点

# T team spawn points
T_spawn_points:
  - [-8.0, -8.0, 0.0]
  - [-7.0, -8.0, 0.0]
  - [-6.0, -8.0, 0.0]

# CT team spawn points
CT_spawn_points:
  - [8.0, 8.0, 0.0]
  - [7.0, 8.0, 0.0]
  - [6.0, 8.0, 0.0]

# safe zones
safe_zones:
  - [-10.0, -10.0, 0.0]
  - [10.0, 10.0, 0.0]

# walls [x, y, width, height]
walls:
  - [0.0, 0.0, 1.0, 4.0]
  - [2.0, 2.0, 4.0, 1.0]

# fiducial markers (unused) [id, x, y, z, orientation] 
fiducial_markers:
  - [1, 1.0, 1.0, 2.0, 0.0]
  - [2, -1.0, 1.0, 2.0, 3.14]
