bomb_site:
  corner1:
    x: -1.26
    y: -0.18
    z: 0.01
  corner2:
    x: 0.88
    y: 1.35
    z: 0.0
patrol_points:
- x: -1.71
  y: -0.78
  z: 0.01
- x: 1.26
  y: -0.6
  z: 0.0
- x: 2.12
  y: -1.22
  z: 0.0
- x: 1.25
  y: 1.47
  z: 0.0
spawn_points:
  CT:
  - x: -1.72
    y: 1.63
    z: 0.01
  - x: -1.21
    y: 1.66
    z: 0.01
  T:
  - x: 0.0
    y: -1.43
    z: 0.01
  - x: 0.44
    y: -1.43
    z: 0.01
