# bomb sites [x, y, z]
bomb_sites:
  - [5.0, 5.0, 0.0]
  - [-5.0, 5.0, 0.0]

# T team spawn points
T_spawn_points:
  - [-8.0, -8.0, 0.0]
  - [-7.0, -8.0, 0.0]
  - [-6.0, -8.0, 0.0]

# CT team spawn points
CT_spawn_points:
  - [8.0, 8.0, 0.0]
  - [7.0, 8.0, 0.0]
  - [6.0, 8.0, 0.0]
