bomb_site:
  site1:
    x: -0.03
    y: -0.22
    z: 0.01
  site2:
    x: 1.45
    y: -0.94
    z: 0.0
patrol_points:
- x: -1.33
  y: -1.17
  z: 0.01
- x: -0.92
  y: 0.79
  z: 0.01
- x: -1.81
  y: 1.53
  z: 0.01
- x: 1.59
  y: -1.37
  z: 0.0
spawn_points:
  CT:
  - x: 1.63
    y: -1.39
    z: 0.0
  - x: 1.06
    y: -1.48
    z: 0.0
  T:
  - x: -0.59
    y: 1.55
    z: 0.01
  - x: 0.2
    y: 1.4
    z: 0.01
