bomb_site:
  site1:
    x: -0.15
    y: -0.58
    z: 0.01
  site2:
    x: 1.53
    y: -1.07
    z: 0.0
patrol_points:
- x: -1.29
  y: -1.12
  z: 0.01
- x: -0.94
  y: 0.81
  z: 0.01
- x: -1.79
  y: 1.58
  z: 0.01
- x: 1.81
  y: 0.96
  z: 0.0
spawn_points:
  CT:
  - x: 1.66
    y: -1.53
    z: 0.0
  - x: 1.08
    y: -1.49
    z: 0.0
  T:
  - x: 0.24
    y: 1.51
    z: 0.01
  - x: -0.26
    y: 1.55
    z: 0.01
