# 炸弹点位置 [x, y, z]
bomb_sites:
  - [5.0, 5.0, 0.0]  # A点
  - [-5.0, 5.0, 0.0]  # B点

# T队出生点
T_spawn_points:
  - [-8.0, -8.0, 0.0]
  - [-7.0, -8.0, 0.0]
  - [-6.0, -8.0, 0.0]

# CT队出生点
CT_spawn_points:
  - [8.0, 8.0, 0.0]
  - [7.0, 8.0, 0.0]
  - [6.0, 8.0, 0.0]

# 安全区域
safe_zones:
  - [-10.0, -10.0, 0.0]
  - [10.0, 10.0, 0.0]

# 墙体位置 [x, y, width, height]
walls:
  - [0.0, 0.0, 1.0, 4.0]
  - [2.0, 2.0, 4.0, 1.0]

# 视觉标记位置 [id, x, y, z, orientation]
fiducial_markers:
  - [1, 1.0, 1.0, 2.0, 0.0]
  - [2, -1.0, 1.0, 2.0, 3.14]
