bomb_site:
  site1:
    x: -0.13
    y: -0.27
    z: 0.01
  site2:
    x: 1.38
    y: -0.89
    z: 0.0
patrol_points:
- x: -1.27
  y: -1.1
  z: 0.01
- x: -0.9
  y: 0.72
  z: 0.01
- x: 0.0
  y: -0.32
  z: 0.01
- x: -0.32
  y: -1.52
  z: 0.01
spawn_points:
  CT:
  - x: 1.53
    y: -1.38
    z: 0.0
  - x: -0.26
    y: -1.17
    z: 0.01
  T:
  - x: -0.98
    y: 0.8
    z: 0.01
  - x: -0.12
    y: 0.9
    z: 0.01
