bomb_site:
  corner1:
    x: -1.29
    y: -0.22
    z: 0.01
  corner2:
    x: 0.79
    y: 1.39
    z: 0.0
patrol_points:
- x: -1.61
  y: -0.81
  z: 0.01
- x: 2.19
  y: -1.3
  z: 0.0
- x: 1.25
  y: -0.55
  z: 0.0
- x: 1.3
  y: 1.4
  z: 0.0
spawn_points:
  CT:
    x: -1.69
    y: 1.65
    z: 0.01
  T:
    x: 0.13
    y: -1.49
    z: 0.01
