shutdown_costmaps: false

controller_frequency: 5.0
controller_patience: 15.0

planner_frequency: 0.5
planner_patience: 5.0

oscillation_timeout: 10.0
oscillation_distance: 0.2

recovery_behavior_enabled: true
clearing_rotation_allowed: true

navfn_global_planner:
  allow_unknown: true

DWAPlannerROS:
  max_vel_x: 0.5
  min_vel_x: -0.5
  max_vel_y: 0.0
  min_vel_y: 0.0
  max_vel_trans: 0.5
  min_vel_trans: 0.1
  max_vel_theta: 1.0
  min_vel_theta: 0.4
  
  acc_lim_x: 2.5
  acc_lim_y: 0.0
  acc_lim_theta: 3.2
  
  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.1
